# Generated by Django 3.2 on 2021-09-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='products',
            new_name='hotels',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('prepaid', 'С предоплатой'), ('canceled', 'Отмененный'), ('finished', 'Завершенный')], default='prepaid', max_length=20),
        ),
    ]
