# Generated by Django 3.2 on 2021-09-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20210903_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveitem',
            old_name='product',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='reserveitem',
            old_name='order',
            new_name='reservation',
        ),
    ]
