# Generated by Django 3.2 on 2021-09-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelreview',
            old_name='hotel',
            new_name='hotel_name',
        ),
    ]
